name: Publish in DockerHub

on:  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
 
    - name: Generate Docker images
      run: mvn spring-boot:build-image -DskipTests
             -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/dev-$(date +%Y%m%d):v2
    - name: Login to DockerHub
      run: docker login
            -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "{{ secrets.DOCKERHUB_TOKEN }}"
    - name: push images to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:v1
